get_db_data automatic parameter determination
fsantini/python-e3dc pull request #57
Opened 2022-02-27 10:29 UTC by mdhom

This PR aims to tackle the enhancement proposed in PR #50. Therefore:
- I introduce a method `get_db_data_timestamp` that takes a UNIX timestamp as a start timestamp and an integer as the timespan being requested. This method is the core request method and makes requests of all kind over all date/time/calender boundaries possible, offers more flexibility
- The original `get_db_data` method now automatically determines the start date and the timespan depending on the given timespan string given (DAY/MONTH/YEAR).
  - In case of DAY, the given startDate is replaced with the same day but with 0am as time, timespan then is 24h
  - In case of MONTH, the given startDate is replaced with the first day of the month the startDate lies within. Timespan then is the number of days of this month (using calender module) times 24h
  - In case of YEAR, the given startDate is replaced with the first of the year the startDate lies within. Timespan is 365 days times 24h
- The output objects contain information on the request they were run for:
  - `get_db_data_timestamp` adds the given `requestTimespan` and `requestTimestamp`
  - `get_db_data` additionally adds a property `requestDateInfo` which is
    - `YYYY` in case of year request
    - `YYYY-mm` in case of month request
    - `YYYY-mm-dd` in case of day request

Can't wait to hear your opinions on that PR. Thanks!

2022-02-28 10:07 UTC, mdhom commented
@vchrisb and @initB10r maybe you could review here

2022-03-01 11:33 UTC, capri1989 commented
Tested your PR and it works fine for me

2022-03-02 13:57 UTC, initB10r commented
> @vchrisb and @initB10r maybe you could review here

I have also tested it and it works as expected. Many  thanks!

2022-03-06 08:18 UTC, vchrisb commented
Thx @mdhom.
I'll look into it.

2022-03-06 09:19 UTC, vchrisb requested changes
please look through my comments and give feedback if the suggested changes aren't appropriate. Thx.

2022-03-06 09:19 UTC, vchrisb commented on e3dc/_e3dc.py
>          """
Update docstring to reflect returned dict.

2022-03-06 09:19 UTC, vchrisb commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
order dict alphabetical
rename `requestTimespan` to `timespanSeconds` and `requestTimestamp` to `startTimestamp`

2022-03-06 09:19 UTC, vchrisb commented on e3dc/_e3dc.py
> +        self, timestampStart: int, timespanSeconds: int, keepAlive=False
rename  `timestampStart` to `startTimestamp` for consistency with `startDate` in `get_db_data`.

2022-03-06 09:19 UTC, vchrisb commented on e3dc/_e3dc.py
> +            data["requestDateInfo"] = requestDateInfo
remove `timespanSeconds` and `startTimestamp` from object and add instead `startDate` and `timespan`.
`startDate` should be the updated date in case of `MONTH` and `YEAR`.

2022-03-06 13:23 UTC, mdhom commented on e3dc/_e3dc.py
> +            data["requestDateInfo"] = requestDateInfo
I think the timespan in seconds could be helpful too, since a month is not always the same period of time. If you would want to e.g. calculate the mean consumption per day of the month, then it would be helpful to have the timespan in seconds already in hand.

2022-03-06 13:26 UTC, mdhom commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
is alphabetical order really necessary here? I thought representing some kind of "logical" order could help understanding the values of the object better. So grouping of these time-related values seemed more logical to me.

2022-03-06 13:36 UTC, mdhom commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
Is alphabetical order really helpful here? I think structuring the returned object by logical coherence is better to understand the individual values. But if there's some kind of rule to always have those objects alphabetical, I can do so of course.

2022-03-06 15:15 UTC, vchrisb commented on e3dc/_e3dc.py
> +        """
`timespanSeconds` is missing in the docstring

2022-03-06 15:19 UTC, vchrisb commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
all other returned objects are (should be) ordered alphabetical.
Alphabetical ordering is the most straight forward way for consistency.

2022-03-06 15:21 UTC, vchrisb commented on e3dc/_e3dc.py
> +            data["requestDateInfo"] = requestDateInfo
ok, please add `timespanSeconds` to the docstring in `get_db_data()`

2022-03-06 15:51 UTC, mdhom commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
ok, then I'll fix that. Do you have any idea how to "sort" the properties of an object? It's kind off difficult for me, because I add some properties after the object was created. I don't really would want to create a new object and manually add all previously existing properties because that is error prone (in case someone adds properties to the underlying method).

2022-03-06 16:03 UTC, vchrisb commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
`{k:v for k,v in sorted(data.items())}` does achieve this I think.

2022-03-06 16:25 UTC, mdhom commented on e3dc/_e3dc.py
> +            "requestTimestamp": timestampStart,
done 👍

2022-03-06 16:30 UTC, vchrisb requested changes

2022-03-06 16:30 UTC, vchrisb commented on e3dc/_e3dc.py
> -        return outObj
Please keep `outObj`, as it is already sorted.

2022-03-06 16:30 UTC, vchrisb commented on e3dc/_e3dc.py
> +        return {k:v for k,v in sorted(outObj.items())}
This will fail in case `outObj is None`
Move the sorting into the if clause and return `outObj`.

2022-03-06 16:42 UTC, vchrisb commented on e3dc/_e3dc.py
> +            return {k: v for k, v in sorted(outObj.items())}
`outObj` should be returned nevertheless it is `None`
Replace `outObj` with the sorted one in the if clause and return `outObj` at the end of the method.

2022-03-06 16:44 UTC, vchrisb requested changes

2022-03-06 16:44 UTC, vchrisb commented on e3dc/_rscpLib.py
> +    packFmt = (  # format of header: little-endian, Uint32 tag, Uint8 type, Uint16 length
not sure how this got introduced.
Black is not updating this for me.

2022-03-06 16:44 UTC, vchrisb commented on e3dc/_rscpLib.py
> +    headerFmt = (  # format of header: little-endian, Uint32 tag, Uint8 type, Uint16 length
not sure how this got introduced.
Black is not updating this for me.

2022-03-06 16:50 UTC, mdhom commented on e3dc/_e3dc.py
> +            return {k: v for k, v in sorted(outObj.items())}
ok, yes, thx

2022-03-06 16:50 UTC, mdhom commented on e3dc/_rscpLib.py
> +    packFmt = (  # format of header: little-endian, Uint32 tag, Uint8 type, Uint16 length
I don't know too, I think it's the line length limitation... I just ran black without any parameters...

2022-03-06 16:55 UTC, mdhom commented on e3dc/_rscpLib.py
> +    packFmt = (  # format of header: little-endian, Uint32 tag, Uint8 type, Uint16 length
github-action black doesn't seem to have a problem with the line length here...

2022-03-06 17:12 UTC, vchrisb approved these changes
LGTM

2022-03-06 17:14 UTC, mdhom commented
thanks for the patience 🤣 next time I'll meet your requirements better, I hope

2022-03-06 17:18 UTC, vchrisb commented on e3dc/_e3dc.py
> +                                                            + " is not between 00:00"
I missed this one. This shouldn't be necessary.
What version of black do you have installed? Latest is `22.1.0`.

2022-03-06 17:19 UTC, mdhom commented on e3dc/_e3dc.py
> +                                                            + " is not between 00:00"
yes, latest (22.1.0). I'm just running `python -m black ./`

2022-03-06 17:30 UTC, mdhom commented on e3dc/_e3dc.py
> +                                                            + " is not between 00:00"
now as I run it, it doesn't change anything anymore... idk..

2022-03-06 17:37 UTC, merged