Add DCB data only if available to avoid crashed
fsantini/python-e3dc pull request #86
Opened 2023-09-27 15:13 UTC by eikowagenknecht

Fixes https://github.com/fsantini/python-e3dc/issues/71

2023-10-04 14:32 UTC, eikowagenknecht commented
Flake8, isort and black formatted now.

2023-10-12 08:59 UTC, vchrisb commented on e3dc/_e3dc.py
> +            # For some devices, no infor for the DCBs exists. Skip those.
typo `infor`

2023-10-12 10:24 UTC, vchrisb reviewed
a few items to discuss

2023-10-12 10:24 UTC, vchrisb commented on e3dc/_e3dc.py
> +                dcbobj["warning"] = res
Is it necessary to check for existence for each of the tags?
If tags get removed, I rather would like this reflected in the code than the tag being silently omitted. From my experience, this isn't happening often.
Hence if all of these Tags are expected, testing for their existence shouldn't be done.

2023-10-12 10:24 UTC, vchrisb commented on e3dc/_e3dc.py
> +            if temps is not None and len(temps) == 3 and temps[1] != "Error":
I guess the tag needs to be `RscpTag.BAT_DCB_ALL_CELL_VOLTAGES` and `voltage` being uses instead of `temps`?

2023-10-12 15:07 UTC, eikowagenknecht commented on e3dc/_e3dc.py
> +                dcbobj["warning"] = res
This seems to heavily depend on your E3DC system. For me, the info object looks like this:

```python
('BAT_DCB_INFO', 'Container',
[('BAT_DCB_INDEX', 'Int32', 0),
('BAT_DCB_LAST_MESSAGE_TIMESTAMP', 'Uint64', 1697122955726),
('BAT_DCB_CURRENT_AVG_30S', 'Float32', -0.5463764667510986),
('BAT_DCB_VOLTAGE_AVG_30S', 'Float32', 392.56317138671875)])
```

So only `currentAvg30s` and `voltageAvg30s` would be filled. The others would put "Null" in the res object.

I do not know which fields will be available for other E3DC systems. Can we say that when one of the others is there, then all of them are? Since I don't have more devices to test and there is no official documentation my approach was to only return available values on a value-by-value basis.

WDYT?

2023-10-13 06:29 UTC, vchrisb commented on e3dc/_e3dc.py
> +                dcbobj["warning"] = res
yeah, all this reverse engineering is difficult...
I still would like to keep the api response object consistent, even if it includes null values. Its intention is not to be easy human readable.
`dcbobj["sensorCount"]`, `dcbobj["temperatures"]`, `dcbobj["seriesCellCount"]`, `dcbobj["voltages"]` should also always be in the output. 
`sensorCount` and `seriesCellCount` wìth a default of `0`. `temperatures` and `voltages` with an empty list `[]`.

`measuredResistance` and `measuredResistanceRun` need to be removed from the docstring. I missed that in the last PR.

2023-10-13 09:56 UTC, eikowagenknecht commented on e3dc/_e3dc.py
> +                dcbobj["warning"] = res
Sure, I modified the code so that the defaults for those 4 values are returned if they don't exist.

How do you want `dcbobj["current"]` etc. be handled? Return a 0, an empty string, "Null", ...?

2023-10-13 11:09 UTC, vchrisb commented on e3dc/_e3dc.py
> +                dcbobj["warning"] = res
I suggest `null`, this is the implicit default

2023-10-13 13:54 UTC, vchrisb requested changes
keep the construction of the `dcbobj`

2023-10-13 13:54 UTC, vchrisb commented on e3dc/_e3dc.py
> -            dcbobj = {
please keep the original construction of the `dcbobj`

2023-10-13 13:54 UTC, vchrisb commented on e3dc/_e3dc.py
> +                dcbobj["voltages"] = voltages
construct the `dcbobj` later

2023-10-14 15:01 UTC, eikowagenknecht commented
Okay, I reverted most of it to the original state. Should now change as little as possible while still fixing the bug.

2023-10-14 16:42 UTC, vchrisb approved these changes

2023-10-14 16:43 UTC, merged