Update list of tags and move to enum
fsantini/python-e3dc pull request #87
Opened 2023-09-28 14:54 UTC by eikowagenknecht

Implements #85

Moving to Enum has the advantage that now only existing tags can be used.

Unfortunately since "BAT_REQ_MEASURED_RESISTANCE" (0x03000130) and "BAT_RUN_MEASURED_RESISTANCE" (0x03800131) don't exist any more, I had to remove those two from the output.

But I think this is a good thing because those two were wrong anyways (see values in screenshots):
- 0x03000130 reported the avg30 current (this is not used any more, but there is 0x03800130 = BAT_INTERNAL_CURRENT_AVG30)
- 0x03800131 reported the avg30 voltage (this is now called BAT_INTERNAL_MTV_AVG30)

I can add those avg30s values to the battery results if you want. Currently those only exist on DCB level.

![image](https://github.com/fsantini/python-e3dc/assets/1475672/54256141-18fe-4a31-9226-f71aac067fdb)

2023-10-02 10:56 UTC, vchrisb commented
Thank you @eikowagenknecht! 🥇 
That is a lot of change.
Can you please separate the two commits into two PRs?

2023-10-02 17:53 UTC, eikowagenknecht commented
Ooops, I intended to do so. The other PR should be fine, but this one needs to be rebased against master. On it.

2023-10-02 18:10 UTC, eikowagenknecht commented
Done. I also fixed the flake8 errors.

2023-10-05 11:59 UTC, vchrisb requested changes
please add `Args` and `Returns` to the docstring.

2023-10-05 11:59 UTC, vchrisb commented on e3dc/_rscpTags.py
> +    """Get datatype as hex."""
`Args` and `Returns` are missing in Docstring

2023-10-05 11:59 UTC, vchrisb commented on e3dc/_rscpTags.py
> +    """Get tag as string."""
`Args` and `Returns` are missing in Docstring

2023-10-05 11:59 UTC, vchrisb commented on e3dc/_rscpTags.py
> +    """Get tag as hex."""
`Args` and `Returns` are missing in Docstring

2023-10-05 11:59 UTC, vchrisb commented on e3dc/_rscpTags.py
> +    """Get tag as RscpTag."""
`Args` and `Returns` are missing in Docstring

2023-10-05 11:59 UTC, vchrisb commented on e3dc/_rscpTags.py
> +    """Get datatype as RscpType."""
`Args` and `Returns` are missing in Docstring

2023-10-05 11:59 UTC, vchrisb commented on e3dc/_rscpTags.py
> +    """Get datatype as string."""
`Args` and `Returns` are missing in Docstring

2023-10-05 12:00 UTC, vchrisb commented
@eikowagenknecht do you potentially already created a script how you generated the `RscpTag`?
I think it would be valuable to add this somewhere to make future updates easier.

2023-10-05 12:01 UTC, vchrisb commented
* would you mind moving `rscpErrorCodes` and `powermeterTypes` also to enum?
* may I suggest using `rscptype` instead of `type_`?

2023-10-10 15:23 UTC, eikowagenknecht commented
> @eikowagenknecht do you potentially already created a script how you generated the `RscpTag`? I think it would be valuable to add this somewhere to make future updates easier.

Sure, I commented and added the script. I put it into a newly created tools directory, if you want it somewhere else I'm happy to move it.

2023-10-10 15:29 UTC, eikowagenknecht commented on e3dc/_rscpTags.py
> +    """Get datatype as string."""
Done

2023-10-10 15:29 UTC, eikowagenknecht commented on e3dc/_rscpTags.py
> +    """Get datatype as RscpType."""
Done

2023-10-10 15:30 UTC, eikowagenknecht commented on e3dc/_rscpTags.py
> +    """Get tag as RscpTag."""
Done

2023-10-10 15:30 UTC, eikowagenknecht commented on e3dc/_rscpTags.py
> +    """Get tag as hex."""
Done

2023-10-10 15:30 UTC, eikowagenknecht commented on e3dc/_rscpTags.py
> +    """Get datatype as hex."""
Done

2023-10-10 15:48 UTC, eikowagenknecht commented
> * would you mind moving `rscpErrorCodes` and `powermeterTypes` also to enum?
> * may I suggest using `rscptype` instead of `type_`?

All done.

2023-10-11 14:43 UTC, vchrisb reviewed
We are getting close to merging this! 💯 
Thank you for sticking to it! 🥇

2023-10-11 14:43 UTC, vchrisb commented on tools/_convert_rscp_tags.py
> +        outfile.write("class RscpTags(Enum):\n")
It needs to be `RscpTag` , there is a `s` too much.

2023-10-11 14:43 UTC, vchrisb commented on tools/_convert_rscp_tags.py
> +            x = string.removeprefix('"').removesuffix('",')
adding a `.split()` is necessary here, as there are a few tags that have a trailing whitespace.

2023-10-11 14:43 UTC, vchrisb commented on README.md
> +- Consider adding yourself to `AUTHORS`
The `README.md` does not need to be updated. There is no difference in using `*` or `-`

2023-10-11 14:43 UTC, vchrisb commented on e3dc/_rscpLib.py
> +    type_ = getRscpType(typeStr)
would you mind using `rscpType`?

2023-10-11 15:27 UTC, eikowagenknecht commented on README.md
> +- Consider adding yourself to `AUTHORS`
The change are the two lines (because I stumbled over the flake8-docstrings requirement):

- Pull request checks will enforce code styling (black, flake8, **flake8-docstrings**, isort)
- Make sure to support Python versions >= 3.7

While both `*` and `-` can be used for lists, I think it's good practice to be consistent. At the beginning of the readme, `-` was used, so I continued with that (and also because my markdownlint plugin formatted the file).

Do you want me to seperate this commit to another PR?

2023-10-11 15:27 UTC, eikowagenknecht commented on tools/_convert_rscp_tags.py
> +        outfile.write("class RscpTags(Enum):\n")
Good catch, fixed.

2023-10-11 15:31 UTC, eikowagenknecht commented on tools/_convert_rscp_tags.py
> +            x = string.removeprefix('"').removesuffix('",')
I believe you mean `.strip()*`? Added it in. Though black clears the double spaces in the next run anyways.

2023-10-11 15:32 UTC, eikowagenknecht commented on e3dc/_rscpLib.py
> +    type_ = getRscpType(typeStr)
Sure. Also renames typeHex to rscptypeHex there for consistency.

2023-10-11 15:41 UTC, merged

2023-10-11 15:55 UTC, fsantini commented
Congratulations :)